### PR TITLE
2.0.0: FIPS 202 SHA-3 standard hash algorithms and SHAVS test vectors, except SHAKE*

### LINKED ISSUE #5: Proper SHA3 implementation?
Hey,

I'm trying to find a SHA3 library for Ruby, but it seems like every library (this one included) is, if I'm not mistaken, using an old version of Keccak for validation, not the actual standardized SHA3.

The most recent SHA3 test vectors say that the hash of the blank string should be:

A7FFC6F8BF1ED76651C14756A061D662F580FF4DE43B49FA82D80A4B80F8434A

however, in this library, it works out to:

C5D2460186F7233C927E7DB2DCC703C0E500B653CA82273B7BFAD8045D85A470 

After some research, I found some pages that calculate both the original keccak and the sha3, and it confirms that the first output is correct. Here's one such page:

https://www.npmjs.com/package/js-sha3

And here's a blank test vector from the original docs:

http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA3-256_Msg0.pdf

Which agrees with everything else, and shows that the output is wrong.

Is there any chance of getting this fixed? Or of adding an option to use the new variation?

### PR DESCRIPTION
**Pull request by skull-squadron**
Closes #5.  #3 can also be closed.

### CODE REVIEW

**Comment by skull-squadron** [comment]
Better test vectors http://csrc.nist.gov/groups/STM/cavp/documents/sha3/sha-3bytetestvectors.zip

**Comment by skull-squadron** [comment]
Ready for merging and release.

cc: @FooBarWidget

**Comment by q9f** [comment]
This should not be merged for historical reasons. If you are looking for SHA3 as per final FIPS standard, use the `sha3` gem.

* https://rubygems.org/gems/sha3

This repository implements a non-final version that is required by many Ethereum centric libraries though. Ethereum developers should use the `keccak` gem, therefore.

* https://rubygems.org/gems/keccak (which I created from this repository)

**Review by mathieujobin — APPROVED** [review]
Now there is the `keccak` gem to keep the 1.x implementation, it can make sense to upgrade this gem to the latest implementation.

**Pull request closed without merging**
